name: open_meteo_api
description: A Dart API Client for the Open Metro API.
version: 1.0.0+1


environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1
  

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.6

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
